### ISSUE TITLE
Fax.File.Pdf.Bytes returns JSON if API returns error 

### ISSUE THREAD

**Issue by jnankin** [phaxio/phaxio-dotnet#11]
If the API returns an error when an attempting to access the fax file (say, 429 rate limit exceeed), fax.File.Pdf.Bytes apparently returns the JSON.  It should raise an exception instead

**Comment by noelherrick** [comment]
ETA on this is US Saturday.

**Comment by noelherrick** [comment]
@jnankin I'm not able to reproduce this issue - I added a test that covers this case and the code works as excepted, throwing an exception if a JSON error is returned.

**Comment by jnankin** [comment]
Ok thanks

**Comment by noelherrick** [comment]
Closing for now.
