### ISSUE TITLE
all parameters in resources should match the API spec

### ISSUE THREAD

**Issue by jnankin** [phaxio/phaxio-dotnet#12]
num_pages should not be PageCount, cost should not be CostInCents, etc.

**Comment by noelherrick** [comment]
Are we ok with doing breaking changes in the API now?

**Comment by jnankin** [comment]
Yes, we should just bump the minor version.  It's that important.

**Comment by noelherrick** [comment]
I think this is finished: I went over it a couple times after this to make sure I'd gotten them all. The only exception is that we can't put the field PhoneNumber on PhoneNumber because C# doesn't allow that (a member name can't be the same as the class).
