### ISSUE TITLE
add an implementation of Fax.Create which allows submission of files by Byte[]

### ISSUE THREAD

**Issue by jnankin** [phaxio/phaxio-dotnet#13]
Users should be able to pass an array of Byte[]s and an array of strings which will be POSTed to Phaxio without having to use File objects.

The 1st Byte[] will contain the image data for a file with a filename that is the 1st string in the filenames string array, etc.

The current implementation using Files can simply call the Byte[] implementation and pass in Byte[]s for the files

**Comment by noelherrick** [comment]
I'll get this one done by Oct. 28

**Comment by noelherrick** [comment]
Just a note, in .NET/C#, FileInfo is not an abstraction over file-like things, it's very much a file, meaning if we were to take the simple implementation mentioned above, it would require writing the Byte[] to disk first, something I'd like to avoid. I'm brainstorming options that keep it simple without running against common practice in .NET

**Comment by julipur** [comment]
any idea when this will be available?

**Comment by jnankin** [comment]
Sorry for the delay, it's in now!  We'll be posting to nuget shortly
