### ISSUE TITLE
'FaxReceipt; does not contain a definition for 'json'

### ISSUE THREAD

**Issue by jgranade** [phaxio/phaxio-dotnet#22]
When you download the solution and try to run Phaxio.Examples.ReceiveCallback you get the error 'Phaxio.Examples.ReceiveCallback.Models.FaxReceipt' does not contain a definition for 'Json'.  In the FaxReceipt class, json is not defined.  It's an easy fix but I wanted to point it.

**Comment by noelherrick** [comment]
@jgranade Thanks for reporting this! I'm starting a fix now. I'll keep you posted on my progress.
